# Generated by Django 5.1.7 on 2025-03-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='padaria',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail da padaria', max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='padaria',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone da padaria', max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
