# Generated by Django 5.1.7 on 2025-04-16 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0002_padaria_email_padaria_telefone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, help_text='Telefone do usuário', max_length=20, null=True, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento do usuário', null=True, verbose_name='Data de Nascimento')),
                ('foto_perfil', models.ImageField(blank=True, help_text='Foto de perfil do usuário', null=True, upload_to='perfil', verbose_name='Foto de Perfil')),
                ('cpf', models.CharField(blank=True, help_text='CPF do usuário', max_length=11, null=True, verbose_name='CPF')),
                ('profissao', models.CharField(blank=True, help_text='Profissão do usuário', max_length=100, null=True, verbose_name='Profissão')),
                ('data_cadastro', models.DateField(auto_now_add=True, help_text='Data de cadastro do usuário', verbose_name='Data de Cadastro')),
                ('endereco', models.OneToOneField(blank=True, help_text='Endereço do usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil', to='padarias.endereco', verbose_name='Endereço')),
                ('user', models.OneToOneField(help_text='Usuário do perfil', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
